version: "3.8"

name: 6-5840

services:
  server:
    image: golang:1.21
    container_name: 6-5840
    hostname: 6-5840
    volumes:
      - ./src:/app
    working_dir: /app
    command: tail -f /dev/null